@startuml

title Communication example of a successful job between SDK and orchestrator
participant SDK as sdk
participant orchestrator as orchestrator

box rabbitmq #white
    queue job_submissions.TYPE          as job_submissions
    queue jobs.ID.result                as job_result
    queue jobs.ID.progress              as job_progress
    queue jobs.ID.status                as job_status
end box


autonumber 1.1
sdk -> job_submissions : JobSubmission
job_submissions -> orchestrator : JobSubmission


group Update SDK about progress
    autonumber inc A
    orchestrator -> job_status : JobStatusUpdate (registered)
    job_status -> sdk : JobStatusUpdate (registered)
    autonumber inc A
    orchestrator -> job_status : JobStatusUpdate (enqueued)
    job_status -> sdk : JobStatusUpdate (enqueued)
    autonumber inc A
    orchestrator -> job_status : JobStatusUpdate (running)
    job_status -> sdk : JobStatusUpdate (running)

    autonumber inc A
    orchestrator -> job_progress : JobProgressUpdate (10%)
    job_progress -> sdk : JobProgressUpdate (10%)
    autonumber inc A
    orchestrator -> job_progress : JobProgressUpdate (50%)
    job_progress -> sdk : JobProgressUpdate (50%)
    autonumber inc A
    orchestrator -> job_progress : JobProgressUpdate (90%)
    job_progress -> sdk : JobProgressUpdate (90%)

    autonumber inc A
    orchestrator -> job_status : JobStatusUpdate (finished)
    job_status -> sdk : JobStatusUpdate (finished)
    autonumber inc A
    orchestrator -> job_progress : JobProgressUpdate (100%)
    job_progress -> sdk : JobProgressUpdate (100%)
end

<style>
note {
  MaximumWidth 200
}
</style>
note right
    <size:18>Remarks</size>
    - The order of status, result & progress updates is undefined.

    <size:18>Queue name variables</size>
    - ""TYPE"": Name of job/workflow.

    - ""ID"":   UUID of job as generated by SDK.

end note

autonumber inc A
orchestrator -> job_result : JobResult (success)
job_result -> sdk : JobResult (success)

@enduml
